[package]
name = "pgn-lexer"
version = "0.1.0"
authors = ["Lakin Wecker <lakin@structuredabstraction.com>"]

[dependencies]
lazy_static = "*"
regex = "^0.2"
memmap = "0.5.2"

[dependencies.nom]
version = "^3.2"
features = ["regexp", "regexp_macros"]

[package]
description = "A lexer for PGN files for chess. Provides an iterator over the tokens from a byte stream."

# These URLs point to more information about the package. These are
# intended to be webviews of the relevant data, not necessarily compatible
# with VCS tools and the like.
# documentation = "..."
# homepage = "..."
repository = "https://github.com/lakinwecker/pgn-lexer"

# This points to a file under the package root (relative to this `Cargo.toml`).
# The contents of this file are stored and indexed in the registry.
readme = "README.md"

# This is a list of up to five keywords that describe this crate. Keywords
# are searchable on crates.io, and you may choose any words that would
# help someone find this crate.
keywords = ["chess", "pgn", "lexer", "tokenizer"]

# This is a list of up to five categories where this crate would fit.
# Categories are a fixed list available at crates.io/category_slugs, and
# they must match exactly.
categories = ["parser-implementations"]

# This is a string description of the license for this package. Currently
# crates.io will validate the license provided against a whitelist of known
# license identifiers from http://spdx.org/licenses/. Multiple licenses can be
# separated with a `/`.
license = " GPL-3.0"

